### ISSUE TITLE
Supports TC 8.1.x?

### ISSUE THREAD

**Issue by fjakop** [mindriven/TeamCity-OpenCoverRunner#5]
I just installed the plugin on TC 8.1.5 without complaints from TC server. I see the plugin as external plugin in the plugins list, but there's no choice for OpenCover-Runner, neither in build-step types nor in .NET Coverage Tool combobox in NUnit-runner.
How ist this plugin activated and used?

**Comment by mindriven** [comment]
Hi. Thanks for using my plugin. It should appear as a build step type, requires no additional activation, should just work after putting it into TC plugins dir and restarting TC. Anything suspicious in TC logs?
I developed it using different version of TC jars, from what I remember it was 8.0. Maybe problem lies there, but if that is the case there should be something in logs.

**Comment by fjakop** [comment]
I found the error: The plugin is compiled wit Java 7, our TC starts wit Java 6 (which is still well supported by TC). I will try to migrate my TC to Java 7/8 and then try again.

**Comment by mindriven** [comment]
OK, so I will close the issue. If you will find it necessary, please reopen it. Good luck with update!

**Comment by fjakop** [comment]
So me again: Update was successful, the build runner is shown in the UI. Now it asks for configuration "Test runner - Runner executable". Is there some documentation about this?
My tests are already run in the build step before by build runner "NUnit".
How I get this thing configured? BTW, I'm Java programmer so I only scratch the surface of C# build process.

**Comment by mindriven** [comment]
Hello again.
Does this help: https://github.com/mindriven/TeamCity-OpenCoverRunner/blob/master/Documentation/nUnitConfig.png ?
Can you skip your tests being run as they are now? Because otherwise you will run them second time with this plugin (longer build). Anyhow, try using configuration from the picture as a guidance and please let me know about the results.

**Comment by fjakop** [comment]
![image](https://cloud.githubusercontent.com/assets/1125261/5900495/1e128860-a56a-11e4-8ee2-0c09eb8a8964.png)

Well, this helps me for understanding the plugin's functionality. I've configured it alike, but TC tells me all my agents are incompatible because of OpenCover-Runner. Are there other prerequisites to the agents besides of .NET installed?

**Comment by fjakop** [comment]
Ok, found the problem. There's an exception while loading the Spring Application Context of the runner on the agents, I will investigate further.
